### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by WentangChen** [ivalab/KGN#1]
HI!
FIrst , thank you for your excellent work.

is the module "models" created manually?  I can not install it by pip.

**Comment by yiyeChen** [comment]
@TiRaMisu1024 

Thanks for your interest in our work, and apology for the late reply.

The "models" module should be included in the repo, was mistakenly "gitignored" due to directory name duplication. This is fixed in the latest commit: d5027f91fe6f1f9a93d6227f7a2a1ce6623cce14. Can you try it again?

**Comment by WentangChen** [comment]
> @TiRaMisu1024
> 
> Thanks for your interest in our work, and apology for the late reply.
> 
> The "models" module should be included in the repo, was mistakenly "gitignored" due to directory name duplication. This is fixed in the latest commit: [d5027f9](https://github.com/ivalab/KGN/commit/d5027f91fe6f1f9a93d6227f7a2a1ce6623cce14). Can you try it again?

thank you for your help! Sorry I missed the message, I would try it at once.
